http://localhost:3000/hero
###
http://localhost:3000/hero/create

###
POST http://localhost:3000/hero/create
Content-Type: application/json

{
    "id": 6,
    "name": "Zilong",
    "type": "Fighter",
    "avatar": "zilong.jpg"
}

###
PATCH http://localhost:3000/hero/update/6
Content-Type: application/json

{
    "name": "Nana",
    "type": "Mage",
    "avatar": "Nana.jpg"
}

###
DELETE http://localhost:3000/hero/6

###
GET http://localhost:3000/hero/detail/2

-------------------------------------------------------------

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe1@gmail.com",
    "password": "123"
}

###
GET  http://localhost:3000/user/5